global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mac-host'
    static_configs:
      - targets: ['mac-host:9100']
        labels:
          instance: ''

  - job_name: "docker-server"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "test-server"
    static_configs:
      - targets: ["node-exporter-test:9100"]