[agent]
  interval = "5s"
  flush_interval = "5s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "pulse-ai-secure-token"
  organization = "pulse-ai"
  bucket = "metrics"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.disk]]

[[inputs.net]]